export enum ERROR_TYPE{
    ERROR="error",
    SUCCESS="success",
    WARNING="warning",
    NONE=""
}
export enum STATUS_CODES
{
    SUCCESS=200,
    FORBIDDEN=403,
    BADREQUEST=400,
    INTERNAL_SERVER_ERROR=500,
    NOT_FOUND=404,
    USER_ALREADY_EXISTS=409,
    UNAUTHORIZED=401,
    NONE=504
}